backend:
  name: git-gateway
  repo: paulosouza9/pipol
  branch: main
  identity_url: https://auth.decapbridge.com/sites/de48105b-97ee-4d2f-81b9-7e8533760489
  gateway_url: https://gateway.decapbridge.com

  # See who did what (optional)
  commit_messages:
    create: Create {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    update: Update {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    delete: Delete {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    uploadMedia: Upload “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    deleteMedia: Delete “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    openAuthoring: Message {{message}} - {{author-name}} <{{author-login}}> via DecapBridge

# Better Decap + Bridge logo (optional)
logo_url: https://decapbridge.com/decapcms-with-bridge.svg

# Add site links in Decap CMS (optional)
site_url: https://www.pipolart.com
# This enables the local proxy server for development
local_backend: true

media_folder: "public/images" # Media files will be stored in the repo under public/images
public_folder: "/images" # The src attribute for uploaded media will begin with /images

collections:
  - name: "products"
    label: "Productos"
    folder: "src/content/products"
    create: true
    slug: "{{id}}"
    identifier_field: name
    fields:
      - {label: "ID", name: "id", widget: "string", hint: "Unique identifier like '1' or 'pipol-1'"}
      - {label: "Nombre", name: "name", widget: "string"}
      - {label: "Precio (Opcional)", name: "price", widget: "string", required: false}
      - {label: "Imagen", name: "image", widget: "image"}
      - label: "Detalles Técnicos"
        name: "details"
        widget: "object"
        fields:
          - {label: "Material", name: "material", widget: "string"}
          - {label: "Acabado", name: "finish", widget: "string"}
          - {label: "Dimensiones", name: "dimensions", widget: "string"}
          - {label: "Autenticidad", name: "authenticity", widget: "string"}
      - {label: "Descripción Markdown", name: "body", widget: "markdown"}

  - name: "news"
    label: "Novedades"
    folder: "src/content/novedades"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Fecha", name: "date", widget: "datetime"}
      - {label: "Imagen", name: "image", widget: "image", required: false}
      - {label: "Contenido", name: "body", widget: "markdown"}
